server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  jackson:
    default-property-inclusion: non_null

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #dev //说明现在是开发环境
  profiles:
    active: dev
  redis:
    database: 11
    host: localhost
    port: 6379
    password: